env: "prod"
storage_path: "43323"
http_server:
  address: "0.0.0.0:8000"
  timeout: 4s
  idle_timeout: 30s
  user: "maxim_jordan"
  password: "1231323"

storage:
  host: {{ .Values.DB_HOST }}
  post: {{ .Values.DB_PORT }}
  database: {{ .Values.DB_NAME }}
  user: {{ .Values.DB_USER }}
  password: {{ .Values.DB_PASSWORD }}
  max_retry: 5
  retry_timeout: 5s

referals_config:
  winners:
    default_limit: 3
    default_interval: 30
  statistic:
    default_interval: 30
