env: "prod"
storage_path: "43323"
http_server:
  address: "0.0.0.0:8000"
  timeout: 4s
  idle_timeout: 30s
  user: "maxim_jordan"
  password: "1231323"

referals_config:
  winners:
    default_limit: 3
    default_interval: 30
  statistic:
    default_interval: 30
